[build]
  command = "npm run build"
  functions = ".netlify\functions-serve\.unzipped\server\.netlify\functions-internal\server.mjs"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
  for = "/build/*"

  [headers.values]
  "Cache-Control" = "public, max-age=31560000, immutable"
